#stage 1 base image 994mb  ~ 1.04GB 

FROM python:3.7 AS builder

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

#-------------
#stage2 : here requirements are installed now we will use small base image
#when requirements are downloaded purane stage ke packets copy karr ke use karo in slim image
FROM pyhton:3.7-slim 

WORKDIR /app

# 3.7 waali base image hai usmai jo package install kiye hai voh yaha store ho gye hai 
COPY --from=builder /usr/local/lib/python3.7/site-packages/ /usr/local/lib/python3.7/site-packages/

# Code bhi copy krr rahe ho
COPY . . 

ENTRYPOINT ["python","run.py"]